server:
  port: 8433
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://192.168.39.157:30443/realms/toolRent
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: false
            maxAge: 3600
      routes:
        - id: clients-service
          uri: http://ms-clients-service:8080
          predicates:
            - Path=/api/clients/**
          filters:
            - RewritePath=/api/clients(?<segment>/?.*), $\{segment}
        - id: clients-service-options
          uri: http://ms-clients-service:8080
          predicates:
            - Path=/api/clients/**
            - Method=OPTIONS