pipeline {
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout scmGit(branches: [[name: '*/eval2-ms-advance']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/PBust0sN/Tingeso-2025-2']])
                dir("Evaluacion-2-Microservicios/microservicio-frontend"){
                    bat 'npm install'
                    bat 'npm run build'
                }
            }
        }
        stage('Build And Push image to Docker Hub'){
            steps{
                dir("Evaluacion-2-Microservicios/microservicio-frontend"){
                    script{
                       withCredentials([string(credentialsId: 'dock', variable: 'DOCKER_TOKEN')]) {
                        bat 'echo %DOCKER_TOKEN% | docker login -u pbust0sn --password-stdin'
                        bat 'docker build -t pbust0sn/microservicio-frontend:latest .'
                        bat 'docker push pbust0sn/microservicio-frontend:latest'
                        bat 'docker logout'
                        }
                    }

                }
            }
        }

        stage('Rollout Deployment') {
            steps {
                script {
                    bat "for /f %i in ('kubectl get deploy -o name ^| findstr microservicio-frontend') do kubectl rollout restart %i"
                }
            }
        }
    }
}